server:
  port: 9095
  address: 0.0.0.0

spring:
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
  datasource:
    url: jdbc:mysql://172.16.20.10:3306/soul?characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2b8
    username: scap
    password: scap@Prepub.2019
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml

soul:
  database:
    dialect: mysql
    init_script: "META-INF/schema.sql"
    init_enable: true
  sync:
    websocket:
      enabled: true
  #      zookeeper:
  #          url: localhost:2181
  #          sessionTimeout: 5000
  #          connectionTimeout: 2000
  #      http:
  #        enabled: true
  #    nacos:
  #      url: localhost:8848
  #      namespace: 1c10d748-af86-43b9-8265-75f487d20c6c
  #      acm:
  #        enabled: false
  #        endpoint: acm.aliyun.com
  #        namespace:
  #        accessKey:
  #        secretKey:
  aes:
    secret:
      key: 2095132720951327
  jwt:
    key: 2095132720951327
  shiro:
    white-list: /,/favicon.*,/static/**,/index**,/plugin,/platform/**,/websocket,/configs/**,/soul-client/**

logging:
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    org.dromara.soul.bonuspoint: info
    org.dromara.soul.lottery: info
    org.dromara.soul: info

swagger:
  enable: true
