# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: "3.9"
services:
  shenyu-mysql:
    restart: always
    image: mysql:5.7
    container_name: shenyu-mysql
    ports:
      - 13310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shenyu
    networks:
      - shenyu
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 30
  shenyu-zk:
    container_name: shenyu-zk
    image: zookeeper:3.5
    restart: always
    networks:
      - shenyu
  shenyu-redis:
    image: redis:6.0-alpine
    container_name: shenyu-redis
    restart: always
    command: redis-server --requirepass abc
    networks:
      - shenyu
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  shenyu-examples-http:
    deploy:
      resources:
        limits:
          memory: 2048M
    container_name: shenyu-examples-http
    image: shenyu-examples-http
    restart: always
    environment:
      - shenyu.client.serverLists=http://shenyu-admin:9095
    healthcheck:
      test: [ "CMD", "wget", "http://shenyu-examples-http:8189/test/path/123?name=tom" ]
      timeout: 2s
      retries: 30
    ports:
      - 8189:8189
    depends_on:
      shenyu-admin:
        condition: service_healthy
    networks:
      - shenyu

  shenyu-admin:
    image: apache/shenyu-admin:2.4.0-SNAPSHOT
    container_name: shenyu-admin
    restart: always
    networks:
      - shenyu
    volumes:
      - type: bind
        source: ./admin-config/schema.sql
        target: /opt/shenyu-admin/conf/schema.sql
    depends_on:
      shenyu-mysql:
        condition: service_healthy
      shenyu-redis:
        condition: service_healthy
    ports:
      - 9095:9095
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - "spring.datasource.url=jdbc:mysql://shenyu-mysql:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false"
      - "spring.datasource.password=root"
      - "shenyu.database.custom_init_script=/opt/shenyu-admin/conf/schema.sql"
    healthcheck:
      test: [ "CMD", "wget", "http://shenyu-admin:9095/actuator/health" ]
      timeout: 2s
      retries: 30
#  from http plugin dockerfile
#  shenyu-integrated-test-http:
#    container_name: shenyu-integrated-test-http
#    image: shenyu-integrated-test-http
#    restart: always
#    deploy:
#      resources:
#        limits:
#          memory: 2048M
#    depends_on:
#      shenyu-examples-http:
#        condition: service_healthy
#    ports:
#      - 9195:9195
#    networks:
#      - shenyu

networks:
  shenyu:
    name: shenyu